# default configuration
baseURL = "https://photography-theme.netlify.app"
languageCode = "en-us"
title = "Lock and Shutter Photography"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

# menu header
[[menu.main]]
URL = "about"
name = "About"
weight = 1


[[menu.main]]
URL = "gallery"
name = "Gallery"
weight = 2


[[menu.main]]
URL = "packages"
name = "Packages"
weight = 3

[[menu.main]]
URL = "contact"
name = "Get in Touch"
weight = 4

# menu footer
[[menu.footer]]
URL = "about"
name = "About"
weight = 1

[[menu.footer]]
URL = "gallery"
name = "Gallery"
weight = 2

[[menu.footer]]
URL = "packages"
name = "Packages"
weight = 3


[[menu.footer]]
URL = "contact"
name = "Get in Touch"
weight = 4

# default parameters
[params]
home = "Home"

logo = "/images/icons/lock-shutter-photography-logo-2.svg"
# contact info
email = "lockandshutterphotography@outlook.com"
address = "Huntington, WV"
# meta description
author = "Nichole Steffey"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 Lock and Shutter Photography"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/xknkvnla" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"

# social site
[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/lockandshutterphotography/?igshid=eyvstsqvaogj"

[[params.social]]
icon = "ti-email"
URL = "mailto:lockandshutterphotography@outlook.com"

