# [build]
#   publish = "exampleSite/public"
#   command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build]
  publish = "/public"
  # command = "cd example-site && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_THEME = "repo"